AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Warning
    System: Warning
    Microsoft: Warning
eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
mysql:
  client:
    server: localhost
    sslmode: none
management: 
  endpoints: 
    cloudfoundry: 
      validateCertificates: false
